### PR TITLE
Properly assign timestamps on insert/update

### PR DESCRIPTION
**Pull request by pidydx**
This alters the MySQLAdvanced datastore to have the database handle creation of timestamps on insert/update since any delays in insert or use of sync=false can cause race conditions.  The unit test for testing None timestamps was also altered to get a before and after insert time and check that the inserted timestamp exists between those two.

[Review on Reviewable](https://reviewable.io/reviews/google/grr/192)

### CODE REVIEW

**Comment by scudette** [comment]
Review status: 0 of 2 files reviewed, 3 unresolved discussions, all commit checks successful.

---

<sup>**[lib/data_store_test.py, line 157 \[r1\]](https://reviewable.io:443/reviews/google/grr/192#-JrJ6dVyR6UkBcU20P_b)** ([raw file](https://github.com/google/grr/blob/71cd43f2517ab3d3c6992a0eb9e2bfb427253f0f/lib/data_store_test.py#L157)):</sup>
need to de-indent now.

---

<sup>**[lib/data_store_test.py, line 164 \[r1\]](https://reviewable.io:443/reviews/google/grr/192#-JrJ6YKj49PZW1wQ76B4)** ([raw file](https://github.com/google/grr/blob/71cd43f2517ab3d3c6992a0eb9e2bfb427253f0f/lib/data_store_test.py#L164)):</sup>
This might break if there is time shift between client and server?

---

<sup>**[lib/data_stores/mysql_advanced_data_store.py, line 222 \[r1\]](https://reviewable.io:443/reviews/google/grr/192#-JrJ6mx0H2h7LVVgk4PP)** ([raw file](https://github.com/google/grr/blob/71cd43f2517ab3d3c6992a0eb9e2bfb427253f0f/lib/data_stores/mysql_advanced_data_store.py#L222)):</sup>
Is the timestamp in seconds or microseconds? Eitherway you need to return an rdfvalue so either RDFDatetime or RDFDatetimeSeconds.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/google/grr/192)

**Comment by pidydx** [comment]
Review status: 0 of 2 files reviewed, 3 unresolved discussions, all commit checks successful.

---

<sup>**[lib/data_store_test.py, line 164 \[r1\]](https://reviewable.io:443/reviews/google/grr/192#-JrJ6YKj49PZW1wQ76B4)** ([raw file](https://github.com/google/grr/blob/71cd43f2517ab3d3c6992a0eb9e2bfb427253f0f/lib/data_store_test.py#L164)):</sup>
This should only break if there is a timeshift between the grr server and the datastore.  This would only be a possibility if you are using a different host for the datastore than you are for running the unit tests.

---

<sup>**[lib/data_stores/mysql_advanced_data_store.py, line 222 \[r1\]](https://reviewable.io:443/reviews/google/grr/192#-JrJ6mx0H2h7LVVgk4PP)** ([raw file](https://github.com/google/grr/blob/71cd43f2517ab3d3c6992a0eb9e2bfb427253f0f/lib/data_stores/mysql_advanced_data_store.py#L222)):</sup>
I am actually a little confused by this one.  I originally had it working using RDFDatetime, but after these changes I had problems with the unit tests.  When I looked at the other datastores they are returning like this and not as rdfvalue.RDFDateTime(row["timestamp"]) so I removed that and they passed.  However, trying to reproduce this now on the latest it passes both ways.  

I also noticed that ResolveMulti was returning using rdfvalueRDFDateTime, but ResolveRegex wasn't.  The field itself is just stored as microseconds in the database.  I was going to convert this to MySQL date time, but there is a bug in MySQL that drops microseconds on insert for values less than 1 second after unixtime(0).  This causes all the unit tests using arbitrary tiny timestamps to fail and I didn't want to rewrite all the unit tests and also risk messing up any unexpected legitimate use of tiny timestamps that might be hiding somewhere.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/google/grr/192)

**Comment by pidydx** [comment]
Review status: 0 of 2 files reviewed, 3 unresolved discussions, all commit checks successful.

---

<sup>**[lib/data_stores/mysql_advanced_data_store.py, line 222 \[r1\]](https://reviewable.io:443/reviews/google/grr/192#-JrJ6mx0H2h7LVVgk4PP)** ([raw file](https://github.com/google/grr/blob/71cd43f2517ab3d3c6992a0eb9e2bfb427253f0f/lib/data_stores/mysql_advanced_data_store.py#L222)):</sup>
Should ResolveMulti and ResolveRegex both return the timestamp as rdfvalue.RDFDateTime or is microseconds as an int sufficient as other datastores appear to do or should they return differently as MySQL originally was.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/google/grr/192)

**Comment by pidydx** [comment]
Review status: 0 of 2 files reviewed, 3 unresolved discussions, some commit checks failed.

---

<sup>**[lib/data_store_test.py, line 157 \[r1\]](https://reviewable.io:443/reviews/google/grr/192#-JrJ6dVyR6UkBcU20P_b)** ([raw file](https://github.com/google/grr/blob/71cd43f2517ab3d3c6992a0eb9e2bfb427253f0f/lib/data_store_test.py#L157)):</sup>
Done

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/google/grr/192)

**Comment by pidydx** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

<sup>**[lib/data_stores/mysql_advanced_data_store.py, line 222 \[r1\]](https://reviewable.io:443/reviews/google/grr/192#-JrJ6mx0H2h7LVVgk4PP)** ([raw file](https://github.com/google/grr/blob/71cd43f2517ab3d3c6992a0eb9e2bfb427253f0f/lib/data_stores/mysql_advanced_data_store.py#L222)):</sup>
I had to revert these back to returning row["timestamp"] directly as microseconds as an integer.  While most of GRR seems to behave with either, the other datastores return as int and the Server Load page throws errors if this is returned as RDFDatetime instead of an integer.  As an integer everything seems to behave as expected.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/google/grr/192)

**Comment by destijl** [comment]
@scudette can you finish off this one?

**Comment by scudette** [comment]
LGTM

**Pull request merged**
