### PR TITLE
Use google.protobuf.Any for argument values

### PR DESCRIPTION
**Pull request by hillu**
This is my attempt at taking care of #530 before 3.2.0 is released. Unfortunately, I don't know if this is enough and I don't really have a way to test. If this is not enough, please give me directions so I can work on completing this in the next few days.

Thanks,
-Hilko

### CODE REVIEW

**Comment by mbushkov** [comment]
Hilko, thanks for the PR.

The changes you made are ok, but only if backwards compatibility is not a concern. If the changes are done in a way they're done in this PR, you won't be able to use new GRR server with any of the older clients and most likely you'll have troubles inspecting older hunts and cron jobs.

While datastore compatibility is a lesser concern, breaking compatibility with older clients is something that we generally tend to avoid.

The proper way to solve the issue would be to add a new field to each protobuf in question. This field should have the same name as the old one. The old one should be renamed to DEPRECATED_[field_name]. 

After that changes in https://github.com/google/grr/blob/master/grr/lib/rdfvalues/structs.py#L988 have to be made so that a new field will take the data from the deprecated field if the data are passed from the older clients. Similarly, when a value is assigned to a new field it has to duplicate it into the DEPRECATED_[field_name] field to maintain backwards compatibility. Most likely we have to add a kind of "legacy_field" annotation to dynamic fields that we have to migrate, so that they know that they have to look into DEPRECATED_[field_name] field for data.

All these changes are not too complicated but doing them without GRR development experience may take time, since you'd have to touch the internals of key GRR components (protos and RDFValues).

As far as I understand, you want to make sure that the proto changes get into the release, so that you can use the API to inspect the data. Good news is that we have changed our release process significantly and have mostly automated it. We intend to do releases periodically (every 3 months), but we also have an opportunity now to cut an out-of-band release if needed.

We can probably do the changes to migrate legacy dynamic fields to google.protobuf.Any within a few weeks. We can then cut a new release candidate and make a new release. Would that be ok for you?

**Comment by hillu** [comment]
Thank you for your detailed explanation and advice. To me, datastore compatibility is just as big a concern as API compatibility. I'll try to implement the the compatibility layer and update this PR in the next few days.

**Comment by mbushkov** [comment]
Hilko, you're welcome! Please feel free to ask questions about the current implementation and about technologies involved (i.e. protobufs). We'll be happy to answer and to help.

**Comment by mbushkov** [comment]
Hi Hilko! Jfyi: we released a 3.2.0.1 GRR version (https://github.com/google/grr/releases/tag/v3.2.0.1). As I said earlier, no worries about the google.protobuf.Any changes not being included into this release - we'll cut a new release as soon as they're in.

**Comment by hillu** [comment]
I haven't been interested in this PR for quite some time, so I am closing it.

**Pull request closed without merging**
