### PR TITLE
netsh arg list fix

### PR DESCRIPTION
**Pull request by pettai**
fix the arg list to netsh

### CODE REVIEW

**Comment by grrrrrrrrr** [comment]
Thanks for the fix!

**Comment by pettai** [comment]
NP. 
btw. did the autobuild jobs fail? 
ubuntu@grr-test:~$ ./google-cloud-sdk/bin/gsutil ls -l gs://autobuilds.grr-response.com/_latest_server_deb/*.deb
 176817042  2018-08-31T13:30:04Z  gs://autobuilds.grr-response.com/_latest_server_deb/grr-server_3.2.3-2_amd64.deb
TOTAL: 1 objects, 176817042 bytes (168.63 MiB)

**Comment by grrrrrrrrr** [comment]
Yeah they are, we noticed too. According to the logs (https://ci.appveyor.com/project/grr/grr-5wmt5/build/1.0.18) there is some sudden permission error uploading to the cloud bucket. We are investigating...

**Comment by grrrrrrrrr** [comment]
@demonchild2112 already had a look and fixed the permissions. There is a new .deb in the bucket now but that one doesn't include this PR yet. We started a new build, should be done in a few minutes...

**Pull request merged**
