### PR TITLE
Additional whitelist command

### PR DESCRIPTION
**Pull request by pettai**
Add whitelist for Windows netsh.exe <…> command, to be able to fetch the windows firewall
configuration.

### CODE REVIEW

**Comment by pettai** [comment]
Proposed Aritfact to fetch Window Firewall Configuration
```
name: WindowsFirewallRules
doc: List Windows Firewall rules.
sources:
- type: COMMAND
  attributes:
    args: ["advfirewall", "firewall", "show", "rule", "name=all"]
    cmd: netsh.exe
labels: [System]
supported_os: [Windows]
```

**Comment by grrrrrrrrr** [comment]
Would you mind filing another PR at https://github.com/ForensicArtifacts/artifacts for the artifact? I spoke with @joachimmetz and having this in the main artifact repo would be best.

**Comment by grrrrrrrrr** [comment]
Thanks for sending this!

**Comment by pettai** [comment]
ack, will do that

**Comment by pettai** [comment]
For reference https://github.com/ForensicArtifacts/artifacts/pull/288

**Pull request merged**
