### PR TITLE
Rename startup.py

### PR DESCRIPTION
**Pull request by jawilson0502**
Found a bug in `grr/gui/admin_ui.py` . It had `from grr.lib import server_startup`, however the corresponding file in `grr/lib` was named `startup.py`.  This caused a bug that did not allow `grr_server --component` to run.

### CODE REVIEW

**Comment by jawilson0502** [comment]
I signed it

**Comment by zbuc** [comment]
Can confirm, this change seems necessary to run GRR from the `master` branch right now.

**Comment by jawilson0502** [comment]
Actually, this PR may not be perfect. `grr/server/data_server/data_server.py` still imports `startup.py`. So renaming this isn't the fix... I can change the code in `grr/gui/admin.py` to use only `startup.py` if that is how it should be done to save the devs some time :smile:

**Comment by grrrrrrrrr** [comment]
Hey,

Thanks for this PR! This change actually went in too early - we are going to rename those files in a future commit but somehow this import change was prematurely committed. The correct fix is to change the import back (for now, until the big rename happens). I'll send a commit that does that.

Cheers,
-Andy

**Comment by grrrrrrrrr** [comment]
Should be fixed in https://github.com/google/grr/commit/9edca58aa45b195a6648eed42493219d7421769c

**Pull request closed without merging**
