### PR TITLE
Bug fixes

### PR DESCRIPTION
**Pull request by pidydx**

### CODE REVIEW

**Comment by pidydx** [comment]
The only problem I am consistently experiencing after these fixes is rekall has errors during install and capstone winds up screwed up somehow with Vagrant and Docker.  However, rerunning the install with pip seems to correct it.  The root cause appears to be in the rekall package and not GRR itself.

**Comment by destijl** [comment]
@scudette for the build dependency changes here, since he is currently working on that. Can you post the actual errors?

**Comment by pidydx** [comment]
Rekall errors during pip install -r requirements.txt
==> grr_server_dev:   Running setup.py bdist_wheel for rekall-core: started
==> grr_server_dev:   Running setup.py bdist_wheel for rekall-core: finished with status 'error'
==> grr_server_dev:   Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Eaanrn/rekall-core/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpfUINC8pip-wheel- --python-tag cp27:
==> grr_server_dev:   Traceback (most recent call last):
==> grr_server_dev:     File "<string>", line 1, in <module>
==> grr_server_dev:   IOError: [Errno 2] No such file or directory: '/tmp/pip-build-Eaanrn/rekall-core/setup.py'
==> grr_server_dev:   
==> grr_server_dev:   ----------------------------------------
==> grr_server_dev:   Failed building wheel for rekall-core
==> grr_server_dev:   Running setup.py clean for rekall-core
==> grr_server_dev:   Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Eaanrn/rekall-core/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" clean --all:
==> grr_server_dev:   Traceback (most recent call last):
==> grr_server_dev:     File "<string>", line 1, in <module>
==> grr_server_dev:   IOError: [Errno 2] No such file or directory: '/tmp/pip-build-Eaanrn/rekall-core/setup.py'
==> grr_server_dev:   
==> grr_server_dev:   ----------------------------------------
==> grr_server_dev:   Failed cleaning build dir for rekall-core

**Comment by pidydx** [comment]
Broken capstone after completion.
vagrant@vagrant-ubuntu-trusty-64:/grr$ ./run_tests.sh 
Running tests...
Traceback (most recent call last):
  File "grr/run_tests.py", line 21, in <module>
    from grr.client import tests
  File "/grr/client/tests.py", line 13, in <module>
    from grr.client.client_actions import tests
  File "/grr/client/client_actions/tests.py", line 12, in <module>
    from grr.client.client_actions import components_test
  File "/grr/client/client_actions/components_test.py", line 13, in <module>
    from grr.client.components.rekall_support import grr_rekall
  File "/grr/client/components/rekall_support/grr_rekall.py", line 21, in <module>
    from rekall import plugins
  File "/usr/local/lib/python2.7/dist-packages/rekall/plugins/__init__.py", line 4, in <module>
    from rekall.plugins import addrspaces
  File "/usr/local/lib/python2.7/dist-packages/rekall/plugins/addrspaces/__init__.py", line 10, in <module>
    from rekall.plugins.addrspaces import ewf
  File "/usr/local/lib/python2.7/dist-packages/rekall/plugins/addrspaces/ewf.py", line 27, in <module>
    from rekall.plugins.tools import ewf
  File "/usr/local/lib/python2.7/dist-packages/rekall/plugins/tools/__init__.py", line 30, in <module>
    from rekall.plugins.tools import disassembler
  File "/usr/local/lib/python2.7/dist-packages/rekall/plugins/tools/disassembler.py", line 25, in <module>
    import capstone
  File "/usr/local/lib/python2.7/dist-packages/capstone/__init__.py", line 230, in <module>
    raise ImportError("ERROR: fail to load the dynamic library.")
ImportError: ERROR: fail to load the dynamic library.

**Comment by pidydx** [comment]
It appears this may be related to needing the latest setuptools to install a pytsk3 that isn't broken.

**Comment by grrrrrrrrr** [comment]
As @destijl already mentioned, this script will probably be replaced soon but let's fix the bugs for now so people can still use head. Thanks!

**Pull request merged**
