### PR TITLE
MySQL hold during initialize

### PR DESCRIPTION
**Pull request by pidydx**
[Review on Reviewable](https://reviewable.io/reviews/google/grr/235)

### CODE REVIEW

**Comment by destijl** [comment]
Thanks for the fix, I've already fixed this internally though and will export shortly.

**Comment by pidydx** [comment]
Some extra mongo cleanup and a MySQL pause

**Comment by destijl** [comment]
This looks good, thanks, can you rebase though? Or just put it into a new PR? Trying to keep the history cleaner. Also, need a new CLA :)

https://cla.developers.google.com/about/google-individual

**Comment by pidydx** [comment]
I am working out getting a new CLA signed, but these two PRs should be covered by the previous CLA since that is when the changes were written and submitted.

**Comment by grrrrrrrrr** [comment]
Yeah this PR should still be covered by the previous CLA, for future patches you will need to renew though. LGTM

**Pull request merged**
