### PR TITLE
Remove single server

### PR DESCRIPTION
**Pull request by pidydx**
- Removed SingleServer in favor of defaulting to separate processes.  This is better for performance and makes a new install a little less confusing when it comes time to start expanding or troubleshooting.
- Changed the default datastore to SQLite for performance and security
- Updated and moved Upstart related configs to a shared location similar to systemd scripts
- Added dataserver startup configs to systemd and corrected them for Upstart

[Review on Reviewable](https://reviewable.io/reviews/google/grr/173)

### CODE REVIEW

**Comment by destijl** [comment]
Review status: 0 of 42 files reviewed, 5 unresolved discussions, all commit checks successful.

---

<sup>**[config/upstart/default/grr-http-server, line 2 \[r2\]](https://reviewable.io:443/reviews/google/grr/173#-Jr-P9_WtNkYpV8Au-Rp)** ([raw file](https://github.com/google/grr/blob/38e7a8b4edb46dfa6bb5e615c6df04362e39d57d/config/upstart/default/grr-http-server#L2)):</sup>
You're also going to have to update the build system that expect these upstart and initd files at these locations.  Do a grep for both. I think at least lib/build.py lib/builders/linux.py and the deb and rpm packaging configs.

---

<sup>**[scripts/install_script_ubuntu.sh, line 221 \[r2\]](https://reviewable.io:443/reviews/google/grr/173#-Jr-NFwAoulGwdr_G7_I)** ([raw file](https://github.com/google/grr/blob/38e7a8b4edb46dfa6bb5e615c6df04362e39d57d/scripts/install_script_ubuntu.sh#L221)):</sup>
Starting $SERVER would be more useful.

---

<sup>**[tools/entry_point_test.py, line 90 \[r2\]](https://reviewable.io:443/reviews/google/grr/173#-Jr-NUBaFPdE24jPioQK)** ([raw file](https://github.com/google/grr/blob/6bae99f9a57ce34e7cdcc3161e69f6e9e18c1c0a/tools/entry_point_test.py#L90)):</sup>
It would be good to replace this with similar tests for each component. It's fairly common for people to introduce minor bugs that mean one of the components won't even start by just coding against unit tests and not running the whole thing.

---

<sup>**[tools/grr_server.py, line 47 \[r2\]](https://reviewable.io:443/reviews/google/grr/173#-Jr-Oi4bQh817iLLPpqF)** ([raw file](https://github.com/google/grr/blob/38e7a8b4edb46dfa6bb5e615c6df04362e39d57d/tools/grr_server.py#L47)):</sup>
get rid of these 3 lines in favour of an else, as below.

---

<sup>**[tools/grr_server.py, line 66 \[r2\]](https://reviewable.io:443/reviews/google/grr/173#-Jr-OcOI8i8CttCLh0dO)** ([raw file](https://github.com/google/grr/blob/38e7a8b4edb46dfa6bb5e615c6df04362e39d57d/tools/grr_server.py#L66)):</sup>
These should probably be elif's with an else that raises.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/google/grr/173)

**Comment by pidydx** [comment]
Review status: 0 of 42 files reviewed, 5 unresolved discussions, all commit checks successful.

---

<sup>**[config/upstart/default/grr-http-server, line 2 \[r2\]](https://reviewable.io:443/reviews/google/grr/173#-Jr-P9_WtNkYpV8Au-Rp)** ([raw file](https://github.com/google/grr/blob/38e7a8b4edb46dfa6bb5e615c6df04362e39d57d/config/upstart/default/grr-http-server#L2)):</sup>
Ah, I thought I caught those, but it looks like I missed them.  I will get those fixed

---

<sup>**[scripts/install_script_ubuntu.sh, line 221 \[r2\]](https://reviewable.io:443/reviews/google/grr/173#-Jr-NFwAoulGwdr_G7_I)** ([raw file](https://github.com/google/grr/blob/38e7a8b4edb46dfa6bb5e615c6df04362e39d57d/scripts/install_script_ubuntu.sh#L221)):</sup>
Done

---

<sup>**[tools/entry_point_test.py, line 90 \[r2\]](https://reviewable.io:443/reviews/google/grr/173#-Jr-NUBaFPdE24jPioQK)** ([raw file](https://github.com/google/grr/blob/6bae99f9a57ce34e7cdcc3161e69f6e9e18c1c0a/tools/entry_point_test.py#L90)):</sup>
I don't understand.  There are already tests for all the individual components.  I just removed the SingleServer test.
Are testAdminUI, testWorker, and testHttpServer not what you are talking about?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/google/grr/173)

**Comment by pidydx** [comment]
Review status: 0 of 44 files reviewed, 5 unresolved discussions, some commit checks pending.

---

<sup>**[tools/grr_server.py, line 47 \[r2\]](https://reviewable.io:443/reviews/google/grr/173#-Jr-Oi4bQh817iLLPpqF)** ([raw file](https://github.com/google/grr/blob/38e7a8b4edb46dfa6bb5e615c6df04362e39d57d/tools/grr_server.py#L47)):</sup>
Done

---

<sup>**[tools/grr_server.py, line 66 \[r2\]](https://reviewable.io:443/reviews/google/grr/173#-Jr-OcOI8i8CttCLh0dO)** ([raw file](https://github.com/google/grr/blob/38e7a8b4edb46dfa6bb5e615c6df04362e39d57d/tools/grr_server.py#L66)):</sup>
Done

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/google/grr/173)

**Comment by LadiesChris** [comment]
Reviewed 40 of 42 files at r1, 3 of 3 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/google/grr/173)

**Comment by destijl** [comment]
The problem with this PR is that it conflates both a relatively simple server-side change (remove single server) with a error-prone and time-consuming-to-test change to the client build (moving upstart scripts around). The client change you need to test by rbuilding all the clients for all the platforms.  There's also some sublety around init and init.d interaction for debian that needs to be correct and tested (i.e. it needs to include both and do the right thing when installed on debian and ubuntu).

Suggest you break out the rename into a separate change, then we can get this in.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---

<sup>**[tools/entry_point_test.py, line 90 \[r2\]](https://reviewable.io:443/reviews/google/grr/173#-Jr-NUBaFPdE24jPioQK)** ([raw file](https://github.com/google/grr/blob/6bae99f9a57ce34e7cdcc3161e69f6e9e18c1c0a/tools/entry_point_test.py#L90)):</sup>
ah yep, sorry, I didn't check the rest of the file and reviewable helpfully collapsed it for me.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/google/grr/173)

**Comment by LadiesChris** [comment]
Sent by Outlook for Android





On Mon, Jun 29, 2015 at 1:15 PM -0700, "Sean Gillespie" <notifications@github.com> wrote:
Closed #173.

---
Reply to this email directly or view it on GitHub:
https://github.com/google/grr/pull/173#event-343433217

**Pull request closed without merging**
