### PR TITLE
fix missing client dirs

### PR DESCRIPTION
**Pull request by pettai**
Add mkdir -p of missing client template directories (docker build now works)

### CODE REVIEW

**Comment by destijl** [comment]
The docker build already works as shown below. The other directories get created earlier. Where did you see a failure?

In any case there's no harm having these extra lines, I'll merge after we next export.

```
$ docker pull grrdocker/grr
Using default tag: latest
latest: Pulling from grrdocker/grr
0a85502c06c9: Pull complete 
0998bf8fb9e9: Pull complete 
a6785352b25c: Pull complete 
e9ae3c220b23: Pull complete 
41a83605143b: Pull complete 
dd784c4a96a3: Pull complete 
a31d5cebca9e: Pull complete 
9f0bfa382b92: Pull complete 
680977027bdf: Pull complete 
6dad442d84e8: Pull complete 
ca46c3a40ced: Pull complete 
ffb701e07e95: Pull complete 
18598dbb90e1: Pull complete 
e923db081c46: Pull complete 
9d9bf562c0ae: Pull complete 
f006d83fbcd6: Pull complete 
4e3ce4c853d4: Pull complete 
772d0444f0b6: Pull complete 
d6b0aa26199e: Pull complete 
ed1a197273cd: Pull complete 
726c3d8cfa69: Pull complete 
949e494614f0: Pull complete 
7d4764b0b284: Pull complete 
0185ebb6e304: Pull complete 
5106edf3d38c: Pull complete 
Digest: sha256:9637cc26b922b90d61c8428d82a52ddd7d1dbe64f2b9b40f871a4d1f3d23a4ae
Status: Downloaded newer image for grrdocker/grr:latest
$ docker run \
> -e EXTERNAL_HOSTNAME="localhost" \
> -e ADMIN_PASSWORD="demo" \
> --ulimit nofile=1048576:1048576 \
> -p 0.0.0.0:8000:8000 -p 0.0.0.0:8080:8080 \
> grrdocker/grr grr
Checking write access on config <YamlParser filename="/etc/grr/grr-server.yaml">
All keys will have a bit length of 2048.
Generating executable signing key
...........+++
.................................+++
Generating driver signing key
.......................+++
........................+++
Generating CA keys
Generating Server keys
Generating Django Secret key (used for xsrf protection etc)
Setting configuration as:

{'Logging.domain': 'localhost', 'Monitoring.emergency_access_email': 'grr-emergency@localhost', 'Monitoring.alert_email': 'grr-monitoring@localhost', 'Client.control_urls': ['http://localhost:8080/control'], 'Datastore.implementation': 'SqliteDataStore', 'AdminUI.url': 'http://localhost:8000'}
Configuration parameters set. You can edit these in /etc/grr/server.local.yaml

Step 3: Adding Admin User
Added user admin.

Step 4: Uploading Memory Drivers to the Database
Signing and uploading /usr/share/grr/binaries/OSXPMem-ng-signed.tar.gz to aff4:/config/drivers/osx/memory/pmem-ng-signed
uploaded aff4:/config/drivers/osx/memory/pmem-ng-signed
Signing and uploading /usr/share/grr/binaries/winpmem_i386_1.6.1.sys to aff4:/config/drivers/windows/memory/winpmem.x86.sys
uploaded aff4:/config/drivers/windows/memory/winpmem.x86.sys
Signing and uploading /usr/share/grr/binaries/winpmem_amd64_1.6.1.sys to aff4:/config/drivers/windows/memory/winpmem.amd64.sys
uploaded aff4:/config/drivers/windows/memory/winpmem.amd64.sys

Step 5: Repackaging clients with new configuration.
Will repack the following clients (debug build):

Repacking : /usr/share/grr/executables/windows/templates/GRR_3.0.7.1_amd64.exe.zip
To :        /usr/share/grr/executables/windows/installers/dbg_GRR_3.0.7.1_amd64.exe

Repacking : /usr/share/grr/executables/windows/templates/GRR_3.0.7.1_i386.exe.zip
To :        /usr/share/grr/executables/windows/installers/dbg_GRR_3.0.7.1_i386.exe

Repacking : /usr/share/grr/executables/linux/templates/grr_3.0.7.1_amd64.deb.zip
To :        /usr/share/grr/executables/linux/installers/dbg_grr_3.0.7.1_amd64.deb

Repacking : /usr/share/grr/executables/linux/templates/grr_3.0.7.1_i386.deb.zip
To :        /usr/share/grr/executables/linux/installers/dbg_grr_3.0.7.1_i386.deb

Repacking : /usr/share/grr/executables/linux/templates/grr_3.0.7.1_amd64.rpm.zip
To :        /usr/share/grr/executables/linux/installers/dbg_grr_3.0.7.1_amd64.rpm

Repacking : /usr/share/grr/executables/linux/templates/grr_3.0.7.1_i386.rpm.zip
To :        /usr/share/grr/executables/linux/installers/dbg_grr_3.0.7.1_i386.rpm

Repacking : /usr/share/grr/executables/darwin/templates/grr_3.0.7.1_amd64.pkg.xar
To :        /usr/share/grr/executables/darwin/installers/dbg_grr_3.0.7.1_amd64.pkg

/usr/share/grr/executables/windows/templates/GRR_3.0.7.1_amd64.exe.zip repacked ok.
/usr/share/grr/executables/windows/templates/GRR_3.0.7.1_i386.exe.zip repacked ok.
/usr/share/grr/executables/linux/templates/grr_3.0.7.1_amd64.deb.zip repacked ok.
/usr/share/grr/executables/linux/templates/grr_3.0.7.1_i386.deb.zip repacked ok.
/usr/share/grr/executables/linux/templates/grr_3.0.7.1_amd64.rpm.zip repacked ok.
/usr/share/grr/executables/linux/templates/grr_3.0.7.1_i386.rpm.zip repacked ok.
/usr/share/grr/executables/darwin/templates/grr_3.0.7.1_amd64.pkg.xar repacked ok.
Will repack the following clients :

Repacking : /usr/share/grr/executables/windows/templates/GRR_3.0.7.1_amd64.exe.zip
To :        /usr/share/grr/executables/windows/installers/GRR_3.0.7.1_amd64.exe

Repacking : /usr/share/grr/executables/windows/templates/GRR_3.0.7.1_i386.exe.zip
To :        /usr/share/grr/executables/windows/installers/GRR_3.0.7.1_i386.exe

Repacking : /usr/share/grr/executables/linux/templates/grr_3.0.7.1_amd64.deb.zip
To :        /usr/share/grr/executables/linux/installers/grr_3.0.7.1_amd64.deb

Repacking : /usr/share/grr/executables/linux/templates/grr_3.0.7.1_i386.deb.zip
To :        /usr/share/grr/executables/linux/installers/grr_3.0.7.1_i386.deb

Repacking : /usr/share/grr/executables/linux/templates/grr_3.0.7.1_amd64.rpm.zip
To :        /usr/share/grr/executables/linux/installers/grr_3.0.7.1_amd64.rpm

Repacking : /usr/share/grr/executables/linux/templates/grr_3.0.7.1_i386.rpm.zip
To :        /usr/share/grr/executables/linux/installers/grr_3.0.7.1_i386.rpm

Repacking : /usr/share/grr/executables/darwin/templates/grr_3.0.7.1_amd64.pkg.xar
To :        /usr/share/grr/executa
bles/darwin/installers/grr_3.0.7.1_amd64.pkg

/usr/share/grr/executables/windows/templates/GRR_3.0.7.1_amd64.exe.zip repacked ok.
/usr/share/grr/executables/windows/templates/GRR_3.0.7.1_i386.exe.zip repacked ok.
/usr/share/grr/executables/linux/templates/grr_3.0.7.1_amd64.deb.zip repacked ok.
/usr/share/grr/executables/linux/templates/grr_3.0.7.1_i386.deb.zip repacked ok.
/usr/share/grr/executables/linux/templates/grr_3.0.7.1_amd64.rpm.zip repacked ok.
/usr/share/grr/executables/linux/templates/grr_3.0.7.1_i386.rpm.zip repacked ok.
/usr/share/grr/executables/darwin/templates/grr_3.0.7.1_amd64.pkg.xar repacked ok.

Initialization complete, writing configuration.
Please restart the service for it to take effect.


Admin UI gui is at http://localhost:8000, clients will poll to http://localhost:8080
```

**Comment by pettai** [comment]
Hi, I did a fork of google/grr on github and did a (local) docker build on that tree

**Comment by destijl** [comment]
Was about to merge this, then realised I need you to sign the CLA :/ Would you mind doing that?
https://cla.developers.google.com/about/google-individual

**Comment by destijl** [comment]
We were still waiting on the CLA, but sean has made the same change in the meantime, so I'll close this one.

**Comment by pettai** [comment]
Sorry, I missed your updates in my mailbox.
CLA signed now, so you should be able to merge this

**Pull request closed without merging**
