### PR TITLE
A fist stab at removing the ResolveRegex interface.

### PR DESCRIPTION
**Pull request by grrrrrrrrr**
There is still a lot of work to be done - there are no actual
implementations yet (except for FakeDataStore) and once we add them,
we will also need more tests - but it's a first step in the right
direction.

[Review on Reviewable](https://reviewable.io/reviews/google/grr/242)

### CODE REVIEW

**Comment by destijl** [comment]
LGTM, some minor comments.

---

Review status: 0 of 23 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[lib/data_store.py, line 327 \[r2\]](https://reviewable.io:443/reviews/google/grr/242#-Jwz8cVbAxDEKzZklt82)** ([raw file](https://github.com/google/grr/blob/0a7677dc69101fc7c0050fdee722401bf8330870/lib/data_store.py#L327)):</sup>
This method provides backwards compatibility for the old method of specifying regexes. Each datastore can move to prefix matching by overriding this method and ResolvePrefix below.

---

<sup>**[lib/data_stores/fake_data_store.py, line 371 \[r2\]](https://reviewable.io:443/reviews/google/grr/242#-JwzB46bRlKXT95rLMm2)** ([raw file](https://github.com/google/grr/blob/0a7677dc69101fc7c0050fdee722401bf8330870/lib/data_stores/fake_data_store.py#L371)):</sup>
should this be else if timestamp is None and then have an else that raises? If you pass the wrong type in here, you silently get the maximum range.

---

<sup>**[lib/data_stores/fake_data_store.py, line 372 \[r2\]](https://reviewable.io:443/reviews/google/grr/242#-JwzBekjodEEillJ_4GM)** ([raw file](https://github.com/google/grr/blob/0a7677dc69101fc7c0050fdee722401bf8330870/lib/data_stores/fake_data_store.py#L372)):</sup>
sys.maxint

---

<sup>**[lib/data_stores/fake_data_store.py, line 414 \[r2\]](https://reviewable.io:443/reviews/google/grr/242#-JwzD-hXLV-fglR8crfT)** ([raw file](https://github.com/google/grr/blob/0a7677dc69101fc7c0050fdee722401bf8330870/lib/data_stores/fake_data_store.py#L414)):</sup>
No idea what is in x[1] v[2] etc. Either use named tuples or add comments.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/google/grr/242)

**Comment by pidydx** [comment]
After this is merged and I get the CLA updated I will spend a bit fixing up MySQLAdvanced to take advantage of this instead of the overly complex regex reduction mess I built.  After this will there be any requirement for the Regex based resolves or can they safely be removed in favor of Prefix based resolves?

Also, if you need me I will be sobbing quietly in the corner lamenting the hours spent regexing a regex so I didn't have to regex. ;)

**Comment by grrrrrrrrr** [comment]
Review status: 0 of 23 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[lib/data_store.py, line 327 \[r2\]](https://reviewable.io:443/reviews/google/grr/242#-Jwz8cVbAxDEKzZklt82)** ([raw file](https://github.com/google/grr/blob/0a7677dc69101fc7c0050fdee722401bf8330870/lib/data_store.py#L327)):</sup>
Done.

---

<sup>**[lib/data_stores/fake_data_store.py, line 371 \[r2\]](https://reviewable.io:443/reviews/google/grr/242#-JwzB46bRlKXT95rLMm2)** ([raw file](https://github.com/google/grr/blob/0a7677dc69101fc7c0050fdee722401bf8330870/lib/data_stores/fake_data_store.py#L371)):</sup>
There are actually some other options, ALL_TIMESTAMPS and NEWEST_TIMESTAMP. I added checks for all of them.

---

<sup>**[lib/data_stores/fake_data_store.py, line 372 \[r2\]](https://reviewable.io:443/reviews/google/grr/242#-JwzBekjodEEillJ_4GM)** ([raw file](https://github.com/google/grr/blob/0a7677dc69101fc7c0050fdee722401bf8330870/lib/data_stores/fake_data_store.py#L372)):</sup>
We used to have sys.maxint but that value is not stable - on Windows this is 32bit max and we can't resolve any current value with a timestamp that low - so we changed to this instead.

---

<sup>**[lib/data_stores/fake_data_store.py, line 414 \[r2\]](https://reviewable.io:443/reviews/google/grr/242#-JwzD-hXLV-fglR8crfT)** ([raw file](https://github.com/google/grr/blob/0a7677dc69101fc7c0050fdee722401bf8330870/lib/data_stores/fake_data_store.py#L414)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/google/grr/242)

**Comment by destijl** [comment]
LGTM still

---

Review status: 0 of 23 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[lib/data_stores/fake_data_store.py, line 414 \[r2\]](https://reviewable.io:443/reviews/google/grr/242#-JwzD-hXLV-fglR8crfT)** ([raw file](https://github.com/google/grr/blob/0a7677dc69101fc7c0050fdee722401bf8330870/lib/data_stores/fake_data_store.py#L414)):</sup>
Might as well change k to attribute_name

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/google/grr/242)

**Pull request merged**
